# Generated by Django 6.0.7 on 2026-07-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='albumes/'),
        ),
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
    ]
