# Generated by Django 6.0.7 on 2026-07-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_portada_artista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
