# Generated by Django 6.0.7 on 2026-07-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_album_fecha_lanzamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancionRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(default='MeloVerse Stream', max_length=200)),
                ('archivo_audio', models.FileField(upload_to='musica_radio/')),
            ],
        ),
    ]
